name: Build and deploy Laravel to Azure Web App - belajar-alfabet

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.1'
          extensions: mbstring, intl, bcmath, pdo_mysql
          tools: composer

      - name: Validate & install composer deps (prod)
        run: |
          composer validate --no-check-publish
          composer install --no-dev --prefer-dist --no-progress --optimize-autoloader

      - name: Laravel optimize (build-time)
        run: |
          php artisan config:cache
          php artisan route:cache
          php artisan view:cache
          php artisan event:cache || true
          php artisan storage:link || true

      - name: Create deployment package
        run: |
          zip -r app.zip . \
            -x ".git/*" ".github/*" "node_modules/*" ".vscode/*" ".DS_Store"

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: laravel-app
          path: app.zip

  deploy:
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: laravel-app
          path: .

      - name: Deploy to Azure Web App
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'belajar-alfabet'
          slot-name: 'Production'
          package: 'app.zip'
          publish-profile: ${{ secrets.AZUREAPPSERVICE_PUBLISHPROFILE_F3D89BDC0B8F47BF8DB5AF41E316A779 }}
